name: "CI: Build Test"

on:
  push:
    branches-ignore:
      - "releases/**"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        qt_version: [6.2.0]
        platform: [ubuntu-20.04, windows-latest, macos-latest]
        include:
          - qt_version: 6.2.0
            additional_arguments: -D QT_DEFAULT_MAJOR_VERSION=6
          - platform: ubuntu-20.04
            make: make
            CXXFLAGS: -Wall -Wextra -pedantic -Werror
            MAKEFLAGS: -j2
          - platform: macos-latest
            make: make
            CXXFLAGS: -Wall -Wextra -pedantic -Werror
            MAKEFLAGS: -j3
          - platform: windows-latest
            make: nmake
            CXXFLAGS: /W4 /WX /MP

    runs-on: ${{ matrix.platform }}
    env:
      CXXFLAGS: ${{ matrix.CXXFLAGS }}
      MAKEFLAGS: ${{ matrix.MAKEFLAGS }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4
	with:
	  submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ matrix.qt_version }}

      - name: Build gpt4all-chat
        run: |
          mkdir build
          cd build
          cmake .. ${{ matrix.additional_arguments }}
          cmake --build .
